### ISSUE TITLE
用户体验之动画

### ISSUE THREAD

**Issue by zhanzizhen** [zhanzizhen/coding-blog#22]
这几年前端的发展很快，特别是 javascript。人们越来越关注 javascript 的新事物，关心怎么提高代码可读性和可维护性。但是，很多人忘了一点，前端工程师的产物是界面和界面交互，提高用户体验是前端开发中非常重要的一点。

动画对于提高用户体验来说太重要了，它可以增加体验舒适度，让用户认知过程更为自然。日常开发中我们有很多可以优化体验的场景，下面列举一些。

### 给你的 color 变化加个动画

```css
#app {
  background-color: #fff;
}
#app:hover {
  background-color: #000;
}
```

```css
#app {
  background-color: #fff;
}
#app:hover {
  background-color: #000;
}
```

如果改成：

```css
#app {
  background-color: #fff;
  transition: background-color 0.4s;
}
#app:hover {
  background-color: #000;
}
```

效果很明显，用户可以感受到变化的过程，这个过程也更自然。
